#!/usr/bin/env node
const packageJson = require('../package.json')

const version = packageJson.version

console.log(`\x1b[32mbricolo\x1b[0m version \x1b[33m${version}\x1b[0m`)
console.log(`
\x1b[33mUsage:\x1b[39m
    command [arguments]

\x1b[33mAvailable commands:\x1b[39m
    \x1b[32mhelp\x1b[39m        Display this same message 👽️
    \x1b[32minit\x1b[39m        Create a default structure for the project (Sass, Typescript).
    \x1b[32mserve\x1b[39m       Starts a build-in PHP serves, live-build Sass and Typescript and live browser reload.
`);
